// Single source of truth for events.
// Used by both the Events page and the homepage "Latest Happenings" widget.

const events = [
  {
    id: 13,
    img: "/assests/events1/dwsim.jpeg",
    title: "DWSIM Workshop",
    des: `Our exclusive DWSIM workshop for chemical engineering students was a huge hit! Participants gathered to learn the fundamentals of process plant modeling using DWSIM, enhancing their skills in process design and optimization.`,
    venue: "Online",
    date: "25-06-2024",
    time: "7:00pm",
    link: "",
    status: "Registration Closed",
  },
  {
    id: 12,
    img: "/assests/events1/Ros.jpeg",
    title: "ROS Workshop",
    des: `An incredible ROS Software Workshop led by Harrison Seby, alumnus and robotics expert from Black Coffee Robotics! Participants gained hands-on experience building and programming virtual robots.`,
    venue: "Online",
    date: "25-06-2024",
    time: "7:00pm",
    link: "",
    status: "Registration Closed",
  },
  {
    id: 11,
    img: "/assests/events1/Robowar.jpeg",
    title: "ROBO WARS",
    des: `Step into the arena of Robowar, where power, precision, and passion collide! This year's battles showcased fierce bots, strategic mastery, and cutting-edge innovation.`,
    venue: "Online",
    date: "25-06-2024",
    time: "7:00pm",
    link: "",
    status: "Registration Closed",
  },
  {
    id: 10,
    img: "/assests/events1/robotics.jpeg",
    title: "Robotics Workshop",
    des: `Ideator GECT successfully hosted an engaging "Introduction to Robotics" workshop with speaker Christo Kollannur, Co-founder of Estro Tech Robotics — covering robotics fundamentals and real-world applications.`,
    venue: "Online",
    date: "25-06-2024",
    time: "7:00pm",
    link: "",
    status: "Registration Closed",
  },
  {
    id: 9,
    img: "/assests/events1/javascript.jpeg",
    title: "JavaScript Workshop",
    des: `Our offline JavaScript workshop, "Build, Create, Innovate," was a resounding success — participants mastered JavaScript fundamentals through intermediate to advanced techniques over three days.`,
    venue: "",
    date: "25-06-2024",
    time: "7:00pm",
    link: "",
    status: "Registration Closed",
  },
  {
    id: 8,
    img: "/assests/thinkercad.jpg",
    title: "TinkerCad Workshop",
    des: "A circuit design & simulation workshop led by alumni Vishak Mohan, diving deep into the world of circuit modeling.",
    venue: "Online",
    date: "25-06-2024",
    time: "7:00pm",
    link: "",
    status: "Registration Closed",
  },
  {
    id: 7,
    img: "/assests/powerpoint.jpg",
    title: "PowerPoint Workshop",
    des: "A workshop covering PowerPoint basics, graphs and charts, quiz-template animations, and advanced presentation techniques.",
    venue: "Room 213",
    date: "6-02-2024",
    time: "4:15pm",
    link: "",
    status: "Registration Closed",
  },
  {
    id: 6,
    img: "/assests/product.jpg",
    title: "Product Design Challenge",
    des: "In partnership with Spotcheck Global — a golden opportunity to design a groundbreaking medical device, with prizes for shortlisted designs.",
    venue: "",
    date: "Deadline: 3-02-2024",
    time: "",
    link: "",
    status: "Registration Closed",
  },
  {
    id: 5,
    img: "/assests/iotwork.jpg",
    title: "IoT Workshop",
    des: "An introduction to the Internet of Things — components, workings, and a live demonstration project.",
    venue: "Ideator room",
    date: "16-11-2023",
    time: "4:15 pm",
    link: "",
    status: "Registration Closed",
  },
  {
    id: 4,
    img: "/assests/placementpgm.jpg",
    title: "Programming",
    des: "A Coding Camp as part of Spectra, teaching coding basics for placement-test preparation — for 3rd and 4th years.",
    venue: "ASAP Hall EC Department",
    date: "5|6|7 Oct 2023",
    time: "5:00 pm",
    link: "",
    status: "Registration Closed",
  },
  {
    id: 3,
    img: "/assests/salvete.jpg",
    title: "Salvete",
    des: "A collaborative brainstorming session fostering partnerships between Ideator and various departments, followed by a tour of the Ideator room.",
    venue: "Respective Departments",
    date: "20 Sep 2023",
    time: "4:15 pm",
    link: "",
    status: "Registration Closed",
  },
  {
    id: 2,
    img: "/assests/event2.png",
    title: "Photography Contest",
    des: "A pre-IDEATO photography contest for freshers, celebrating engineering in everyday life.",
    venue: "",
    date: "Submission: 19 Sep 2023",
    time: "",
    link: "",
    status: "Registration Closed",
  },
  {
    id: 1,
    img: "/assests/cpwork2023.jpg",
    title: "C Programming Workshop",
    des: "An exam-oriented C Programming workshop as part of the Spectra workshop series.",
    venue: "Online",
    date: "29|30|31 July 2023",
    time: "6:30pm",
    link: "",
    status: "Registration Closed",
  },
];

export default events;